name = "Planets and Portals 2"
author = "_Shortman"
version = "dev 0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f823db95e8352e4f5abc7753a2f5c6c9aee36bd8ded4acfd9bee6a9909bc90fe"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
