name = "Planets and Portals 2"
author = "_Shortman"
version = "dev 0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdad9783aaf658ac6ec69b1ae44a1b5e6dfcccb0f482adf57d2f07f3fba7ccb2"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
