name = "Planets and Portals 2"
author = "_Shortman"
version = "dev 0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86911ae91e0e2a3cdc61b2e92aac35a4021cf99c0a09410fdca9617fdd4a8844"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
