name = "Typewryttr"
author = "_Shortman"
version = "dev 1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb9abd3f628c535fba28906fe45df0b075d62feefb8560efe0899e95086798df"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
