name = "Typewryttr"
author = "_Shortman"
version = "dev 1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "879659dca4322eab23aca5078e205ed8ed65275a327881d8bb7c8598b73e23a3"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
