name = "Typewryttr"
author = "_Shortman"
version = "dev 1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f02c95e8f4f6e0aa0ddb363e8fb37b59bba9088b597bc5b3760736830816895"

[versions]
fabric = "0.15.10"
minecraft = "1.18.2"
